airports:
  app:
    name: airports-assembly
    replicaCount: 1
    container:
      name: airports-assembly
      image: barbhua786/airports-assembly
      tag: 1.0.1
      containerPort: 8080
      livenessProbe:
        path: /health/live
        port: 8080
        failureThreshold: 3
        initialDelaySeconds: 10
        periodSeconds: 15
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        path: /health/ready
        port: 8080
        failureThreshold: 3
        initialDelaySeconds: 10
        periodSeconds: 15
        successThreshold: 1
        timeoutSeconds: 5
  service:
    name: airports-svc
    port: 8080
    targetPort: 8080