apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.service.name }}
spec:
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.targetPort }}
  type: {{ .Values.nginx.service.type }}
  selector:
    app: {{ .Values.nginx.name }}
