countries:
  app:
    name: countries-assembly
    replicaCount: 1
    container:
      name: countries-assembly
      image: barbhua786/countries-assembly
      tag: 1.0.1
      containerPort: 8080
      livenessProbe:
        path: /health/live
        port: 8080
        initialDelaySeconds: 60
        periodSeconds: 5
        timeoutSeconds: 15
      readinessProbe:
        path: /health/ready
        port: 8080
        initialDelaySeconds: 60
        periodSeconds: 5
        timeoutSeconds: 15
  service:
    name: countries-svc
    port: 8080
    targetPort: 8080